import { create } from 'zustand';

export type Language = 'en' | 'bn';

interface LanguageState {
  language: Language;
  setLanguage: (lang: Language) => void;
  toggleLanguage: () => void;
}

export const useLanguageStore = create<LanguageState>((set) => {
  // Get initial language from localStorage or browser settings
  const storedLang = typeof window !== 'undefined' ? (localStorage.getItem('tazu_language') as Language) : 'en';
  const initialLang: Language = storedLang === 'bn' || storedLang === 'en' ? storedLang : 'en';

  return {
    language: initialLang,
    setLanguage: (lang: Language) => {
      localStorage.setItem('tazu_language', lang);
      set({ language: lang });
      window.dispatchEvent(new CustomEvent('tazu-language-changed', { detail: lang }));
    },
    toggleLanguage: () => {
      set((state) => {
        const nextLang: Language = state.language === 'en' ? 'bn' : 'en';
        localStorage.setItem('tazu_language', nextLang);
        window.dispatchEvent(new CustomEvent('tazu-language-changed', { detail: nextLang }));
        return { language: nextLang };
      });
    },
  };
});

// Structural UI Translations Dictionary
export const translations = {
  en: {
    // Navigation & Drawer / Header
    home: 'Home',
    categories: 'Categories',
    offers: 'Offers',
    support: 'Support',
    account: 'Account',
    login: 'Login',
    signIn: 'Sign In',
    register: 'Register',
    logout: 'Logout',
    settings: 'Settings',
    language: 'Language',
    allCategories: 'All Categories',
    quickMenu: 'Quick Menu',
    siteLinks: 'Site Links',
    visitWeb: 'Visit Web',
    browseCategories: 'Browse Categories',
    exploreProducts: 'Explore Products',
    viewAll: 'View All',
    search: 'Search...',
    searchBtn: 'Search',
    cameraSearch: 'Camera Search',
    cart: 'Cart',
    wishlist: 'Wishlist',
    orders: 'Orders',
    myOrders: 'My Orders',
    myProfile: 'My Profile',
    myAddresses: 'My Addresses',
    recentlyViewed: 'Recently Viewed',
    trackOrder: 'Track Order',
    notifications: 'Notifications',
    couponsOffers: 'Coupons & Offers',
    helpSupport: 'Help & Support',
    welcome: 'Welcome',
    welcomeGuest: 'Welcome, Guest',
    guestDesc: 'Sign in to access your account',
    menu: 'Menu',
    shopByCategory: 'Shop By Category',
    myAccount: 'My Account',
    more: 'More',

    // Checkout Page
    checkout: 'Checkout',
    customerName: 'Customer Name',
    fullName: 'Full Name',
    mobileNumber: 'Mobile Number',
    address: 'Address',
    district: 'District',
    upazila: 'Upazila',
    selectDistrict: 'Select District',
    selectUpazila: 'Select Upazila',
    quantity: 'Quantity',
    price: 'Price',
    total: 'Total',
    subtotal: 'Subtotal',
    deliveryCharge: 'Delivery Charge',
    confirmOrder: 'Confirm Order',
    placeOrder: 'Place Order',
    cashOnDelivery: 'Cash on Delivery',
    orderSummary: 'Order Summary',
    promoCode: 'Promo Code / Coupon Code',
    apply: 'Apply',
    orderNote: 'Order Note (Optional)',
    paymentMethod: 'Payment Method',
    items: 'Items',
    shippingAddress: 'Shipping Address',
    orderPlacedSuccess: 'Order Placed Successfully!',
    required: 'Required',
    requiredField: 'This field is required',
    invalidMobile: 'Please enter a valid 11-digit mobile number',

    // Product Detail Page
    buyNow: 'Buy Now',
    addToCart: 'Add To Cart',
    description: 'Description',
    reviews: 'Reviews',
    specifications: 'Specifications',
    outOfStock: 'Out of stock',
    inStock: 'In Stock',
    freeDelivery: 'Free Delivery',
    coins: 'Coins',
    relatedProducts: 'Related Products',
    youMayAlsoLike: 'You May Also Like',
    share: 'Share',
    download: 'Download',
    back: 'Back',
    productCode: 'Product Code',
    category: 'Category',
    brand: 'Brand',
    rating: 'Rating',
    writeReview: 'Write Review',
    copiedLink: 'Product link copied successfully',
    savedWishlist: 'Product saved in wishlist',
    removedWishlist: 'Product removed from wishlist',
    preparingDownload: 'Preparing download...',
    downloadSuccess: 'Image downloaded successfully!',

    // Cart & Wishlist Pages
    yourCartIsEmpty: 'Your Cart is Empty',
    yourWishlistIsEmpty: 'Your Wishlist is Empty',
    shopNow: 'Shop Now',
    continueShopping: 'Continue Shopping',
    proceedToCheckout: 'Proceed to Checkout',
    remove: 'Remove',
    clearCart: 'Clear Cart',
    itemAddedToCart: 'Item added to cart',

    // Search & Filter
    searchProducts: 'Search Products',
    filter: 'Filter',
    sortBy: 'Sort By',
    lowToHigh: 'Price: Low to High',
    highToLow: 'Price: High to Low',
    newest: 'Newest',
    popularity: 'Popularity',
    noProductsFound: 'No products found',
    clearFilters: 'Clear Filters',
    allProducts: 'All Products',

    // Auth & Account
    emailOrPhone: 'Email or Mobile Number',
    password: 'Password',
    forgotPassword: 'Forgot Password?',
    dontHaveAccount: "Don't have an account?",
    registerNow: 'Register Now',
    alreadyHaveAccount: 'Already have an account?',
    editProfile: 'Edit Profile',
    saveChanges: 'Save Changes',
    orderHistory: 'Order History',
    orderDetails: 'Order Details',
    orderStatus: 'Order Status',
    pending: 'Pending',
    processing: 'Processing',
    shipped: 'Shipped',
    delivered: 'Delivered',
    cancelled: 'Cancelled',
    orderNumber: 'Order No',
    orderDate: 'Order Date',

    // General & Footer
    flashSale: 'Flash Sale',
    bestSelling: 'Best Selling',
    trending: 'Trending',
    customerService: 'Customer Service',
    quickLinks: 'Quick Links',
    privacyPolicy: 'Privacy Policy',
    termsConditions: 'Terms & Conditions',
    refundPolicy: 'Refund Policy',
    aboutUs: 'About Us',
    contactUs: 'Contact Us',
    cancel: 'Cancel',
    confirm: 'Confirm',
    close: 'Close',
    logoutConfirmation: 'Are you sure you want to logout?',
  },
  bn: {
    // Navigation & Drawer / Header
    home: 'হোম',
    categories: 'ক্যাটাগরি',
    offers: 'অফার',
    support: 'সাপোর্ট',
    account: 'অ্যাকাউন্ট',
    login: 'লগইন',
    signIn: 'লগইন করুন',
    register: 'রেজিস্ট্রেশন',
    logout: 'লগআউট',
    settings: 'সেটিংস',
    language: 'ভাষা',
    allCategories: 'সকল ক্যাটাগরি',
    quickMenu: 'কুইক মেনু',
    siteLinks: 'সাইট লিংক',
    visitWeb: 'ওয়েবসাইট ভিজিট',
    browseCategories: 'ক্যাটাগরি ব্রাউজ করুন',
    exploreProducts: 'পণ্যসমূহ এক্সপ্লোর করুন',
    viewAll: 'সবগুলো দেখুন',
    search: 'অনুসন্ধান করুন...',
    searchBtn: 'খুঁজুন',
    cameraSearch: 'ক্যামেরা সার্চ',
    cart: 'কার্ট',
    wishlist: 'উইশলিস্ট',
    orders: 'অর্ডারসমূহ',
    myOrders: 'আমার অর্ডার',
    myProfile: 'আমার প্রোফাইল',
    myAddresses: 'আমার ঠিকানা',
    recentlyViewed: 'সম্প্রতি দেখা পণ্য',
    trackOrder: 'অর্ডার ট্র্যাক করুন',
    notifications: 'নোটিফিকেশন',
    couponsOffers: 'কুপন ও অফার',
    helpSupport: 'সাহায্য ও সাপোর্ট',
    welcome: 'স্বাগতম',
    welcomeGuest: 'স্বাগতম, অতিথি',
    guestDesc: 'আপনার অ্যাকাউন্টে প্রবেশ করতে সাইন ইন করুন',
    menu: 'মেনু',
    shopByCategory: 'ক্যাটাগরি অনুযায়ী কেনাকাটা করুন',
    myAccount: 'আমার অ্যাকাউন্ট',
    more: 'আরও',

    // Checkout Page
    checkout: 'চেকআউট',
    customerName: 'ক্রেতার নাম',
    fullName: 'সম্পূর্ণ নাম',
    mobileNumber: 'মোবাইল নম্বর',
    address: 'ঠিকানা',
    district: 'জেলা',
    upazila: 'উপজেলা',
    selectDistrict: 'জেলা নির্বাচন করুন',
    selectUpazila: 'উপজেলা নির্বাচন করুন',
    quantity: 'পরিমাণ',
    price: 'মূল্য',
    total: 'মোট',
    subtotal: 'উপমোট',
    deliveryCharge: 'ডেলিভারি চার্জ',
    confirmOrder: 'অর্ডার নিশ্চিত করুন',
    placeOrder: 'অর্ডার নিশ্চিত করুন',
    cashOnDelivery: 'ক্যাশ অন ডেলিভারি',
    orderSummary: 'অর্ডার সারসংক্ষেপ',
    promoCode: 'প্রমো কোড / কুপন কোড',
    apply: 'প্রয়োগ করুন',
    orderNote: 'স্পেশাল নোট (ঐচ্ছিক)',
    paymentMethod: 'পেমেন্ট পদ্ধতি',
    items: 'আইটেম',
    shippingAddress: 'শিপিং ঠিকানা',
    orderPlacedSuccess: 'অর্ডার সফলভাবে সম্পন্ন হয়েছে!',
    required: 'আবশ্যক',
    requiredField: 'এই ঘরটি পূরণ করা আবশ্যক',
    invalidMobile: 'অনুগ্রহ করে সঠিক ১১ ডিজিটের মোবাইল নম্বর দিন',

    // Product Detail Page
    buyNow: 'এখনই কিনুন',
    addToCart: 'কার্টে যোগ করুন',
    description: 'বর্ণনা',
    reviews: 'রিভিউসমূহ',
    specifications: 'স্পেসিফিকেশন',
    outOfStock: 'স্টক শেষ',
    inStock: 'স্টকে আছে',
    freeDelivery: 'ফ্রি ডেলিভারি',
    coins: 'কয়েন',
    relatedProducts: 'সম্পর্কিত পণ্যসমূহ',
    youMayAlsoLike: 'আপনার পছন্দ হতে পারে',
    share: 'শেয়ার করুন',
    download: 'ডাউনলোড',
    back: 'পিছনে যান',
    productCode: 'পণ্য কোড',
    category: 'ক্যাটাগরি',
    brand: 'ব্র্যান্ড',
    rating: 'রেটিং',
    writeReview: 'রিভিউ লিখুন',
    copiedLink: 'পণ্য লিংক সফলভাবে কপি করা হয়েছে',
    savedWishlist: 'পণ্য উইশলিস্টে সংরক্ষণ করা হয়েছে',
    removedWishlist: 'পণ্য উইশলিস্ট থেকে সরানো হয়েছে',
    preparingDownload: 'ডাউনলোড প্রস্তুত করা হচ্ছে...',
    downloadSuccess: 'ছবি সফলভাবে ডাউনলোড হয়েছে!',

    // Cart & Wishlist Pages
    yourCartIsEmpty: 'আপনার কার্ট খালি',
    yourWishlistIsEmpty: 'আপনার উইশলিস্ট খালি',
    shopNow: 'এখনই কেনাকাটা করুন',
    continueShopping: 'কেনাকাটা চালিয়ে যান',
    proceedToCheckout: 'চেকআউটে যান',
    remove: 'সরান',
    clearCart: 'কার্ট খালি করুন',
    itemAddedToCart: 'পণ্যটি কার্টে যোগ করা হয়েছে',

    // Search & Filter
    searchProducts: 'পণ্য খুঁজুন',
    filter: 'ফিল্টার',
    sortBy: 'ক্রমানুসারে',
    lowToHigh: 'কম থেকে বেশি দাম',
    highToLow: 'বেশি থেকে কম দাম',
    newest: 'সর্বশেষ পণ্য',
    popularity: 'জনপ্রিয়তা',
    noProductsFound: 'কোনো পণ্য পাওয়া যায়নি',
    clearFilters: 'ফিল্টার মুছুন',
    allProducts: 'সকল পণ্য',

    // Auth & Account
    emailOrPhone: 'ইমেইল বা মোবাইল নম্বর',
    password: 'পাসওয়ার্ড',
    forgotPassword: 'পাসওয়ার্ড ভুলে গেছেন?',
    dontHaveAccount: 'অ্যাকাউন্ট নেই?',
    registerNow: 'এখনই রেজিস্ট্রেশন করুন',
    alreadyHaveAccount: 'ইতিমধ্যে অ্যাকাউন্ট আছে?',
    editProfile: 'প্রোফাইল এডিট করুন',
    saveChanges: 'পরিবর্তন সংরক্ষণ করুন',
    orderHistory: 'অর্ডারের ইতিহাস',
    orderDetails: 'অর্ডারের বিবরণ',
    orderStatus: 'অর্ডারের স্ট্যাটাস',
    pending: 'পেন্ডিং',
    processing: 'প্রসেসিং',
    shipped: 'শিপড',
    delivered: 'ডেলিভার্ড',
    cancelled: 'বাতিল',
    orderNumber: 'অর্ডার নম্বর',
    orderDate: 'অর্ডারের তারিখ',

    // General & Footer
    flashSale: 'ফ্ল্যাশ সেল',
    bestSelling: 'সর্বোচ্চ বিক্রীত',
    trending: 'ট্রেন্ডিং',
    customerService: 'কাস্টমার সার্ভিস',
    quickLinks: 'কুইক লিংক',
    privacyPolicy: 'গোপনীয়তা নীতি',
    termsConditions: 'শর্তাবলী',
    refundPolicy: 'রিফান্ড নীতি',
    aboutUs: 'আমাদের সম্পর্কে',
    contactUs: 'যোগাযোগ করুন',
    cancel: 'বাতিল',
    confirm: 'নিশ্চিত করুন',
    close: 'বন্ধ করুন',
    logoutConfirmation: 'আপনি কি নিশ্চিত যে আপনি লগআউট করতে চান?',
  },
};

// Helper hook for functional components
export function useTranslation() {
  const language = useLanguageStore((state) => state.language);
  const t = translations[language] || translations.en;
  return { language, t };
}
